name: Push
on:
  push:
    branches:
      - '*.x'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        env:
          GITHUB_EVENT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_EVENT"
